services:
  - type: web
    name: portfolio-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production

  - type: web
    name: portfolio-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: portfolio-backend
          type: web
          property: host
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
